// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgy2SfYrXgsZ9JgnBDRR6clKYQylQ-NCA',
    appId: '1:895146229761:web:9e32e0e4ce143d86928000',
    messagingSenderId: '895146229761',
    projectId: 'autofix-car',
    authDomain: 'autofix-car.firebaseapp.com',
    storageBucket: 'autofix-car.firebasestorage.app',
    measurementId: 'G-0NM30PW961',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjQZWUBr855e3UPrYIwYqtPwP3JlICjLM',
    appId: '1:895146229761:android:3f3fc54c1824bda1928000',
    messagingSenderId: '895146229761',
    projectId: 'autofix-car',
    storageBucket: 'autofix-car.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDSdOrlNakAd6pbmi19EWciMV_xXH8-h8',
    appId: '1:895146229761:ios:bbfce021875cd191928000',
    messagingSenderId: '895146229761',
    projectId: 'autofix-car',
    storageBucket: 'autofix-car.firebasestorage.app',
    iosBundleId: 'com.example.autofixCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDSdOrlNakAd6pbmi19EWciMV_xXH8-h8',
    appId: '1:895146229761:ios:bbfce021875cd191928000',
    messagingSenderId: '895146229761',
    projectId: 'autofix-car',
    storageBucket: 'autofix-car.firebasestorage.app',
    iosBundleId: 'com.example.autofixCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgy2SfYrXgsZ9JgnBDRR6clKYQylQ-NCA',
    appId: '1:895146229761:web:a016cd9a98471e82928000',
    messagingSenderId: '895146229761',
    projectId: 'autofix-car',
    authDomain: 'autofix-car.firebaseapp.com',
    storageBucket: 'autofix-car.firebasestorage.app',
    measurementId: 'G-MZKS0LVSTZ',
  );
}
