// lib/models/faq_item.dart
class FAQItem {
  final String?
  id; // Made nullable as it might be null before creation on backend
  final String question;
  final String answer;
  final int order; // To sort FAQs if needed, lower number comes first

  FAQItem({
    this.id,
    required this.question,
    required this.answer,
    this.order = 0, // Default order
  });

  factory FAQItem.fromJson(Map<String, dynamic> json) {
    return FAQItem(
      id: json['id'] as String?, // Parse as nullable String
      question: json['question'] as String,
      answer: json['answer'] as String,
      order: json['order'] as int? ?? 0, // Handle optional order, default to 0
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // ID is usually generated by the backend on creation
      'question': question,
      'answer': answer,
      'order': order,
    };
  }

  FAQItem copyWith({String? id, String? question, String? answer, int? order}) {
    return FAQItem(
      id: id ?? this.id,
      question: question ?? this.question,
      answer: answer ?? this.answer,
      order: order ?? this.order,
    );
  }
}
