// lib/models/notification_item.dart
class NotificationItem {
  final String? id; // Document ID from backend, made nullable for new items
  final String userId; // The UID of the user this notification is for
  final String title;
  final String message;
  final DateTime timestamp;
  final String? imageUrl;
  final bool isRead;
  final String? type; // e.g., 'alert', 'promotion', 'update'
  final Map<String, dynamic>?
  data; // Optional: additional data (e.g., link to a specific scan)

  NotificationItem({
    this.id, // Made nullable
    required this.userId,
    required this.title,
    required this.message,
    this.imageUrl, // Made optional/nullable
    required this.timestamp,
    this.isRead = false,
    this.type,
    this.data,
  });

  factory NotificationItem.fromJson(Map<String, dynamic> json) {
    // Attempt to parse timestamp from different JSON formats
    DateTime parsedTimestamp;
    if (json['timestamp'] is String) {
      parsedTimestamp = DateTime.parse(json['timestamp'] as String);
    } else if (json['timestamp'] is int) {
      parsedTimestamp = DateTime.fromMillisecondsSinceEpoch(
        json['timestamp'] as int,
      );
    } else if (json['timestamp'] is Map &&
        json['timestamp'].containsKey('_seconds')) {
      parsedTimestamp = DateTime.fromMillisecondsSinceEpoch(
        json['timestamp']['_seconds'] * 1000 +
            (json['timestamp']['_nanoseconds'] ?? 0) ~/ 1000000,
      );
    } else {
      parsedTimestamp = DateTime.now(); // Fallback
    }

    return NotificationItem(
      id: json['id'] as String?, // Parse as nullable String
      userId: json['user_id'] as String,
      title: json['title'] as String,
      message: json['message'] as String,
      timestamp: parsedTimestamp,
      isRead: json['is_read'] as bool? ?? false,
      imageUrl: json['image_url'] as String?, // Parse imageUrl
      type: json['type'] as String?,
      data: json['data'] as Map<String, dynamic>?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // ID is usually generated by the backend on creation
      'user_id': userId,
      'title': title,
      'message': message,
      'image_url': imageUrl,
      'timestamp': timestamp.toIso8601String(),
      'is_read': isRead,
      'type': type,
      'data': data,
    };
  }

  NotificationItem copyWith({
    String? id,
    String? userId,
    String? title,
    String? message,
    String? imageUrl, // Included imageUrl in copyWith
    DateTime? timestamp,
    bool? isRead,
    String? type,
    Map<String, dynamic>? data,
  }) {
    return NotificationItem(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      title: title ?? this.title,
      message: message ?? this.message,
      imageUrl: imageUrl ?? this.imageUrl,
      timestamp: timestamp ?? this.timestamp,
      isRead: isRead ?? this.isRead,
      type: type ?? this.type,
      data: data ?? this.data,
    );
  }
}
